CREATE TABLE markets (
  market_id       TEXT PRIMARY KEY,
  base_asset      TEXT,
  quote_asset     TEXT,
  price_precision SMALLINT NOT NULL,
  qty_precision   SMALLINT NOT NULL,
  tick_size       BIGINT NOT NULL,
  lot_size        BIGINT NOT NULL,
  min_order_qty   BIGINT,
  max_order_qty   BIGINT,
  max_order_value BIGINT,
  max_depth       INT DEFAULT 0,
  features        INT NOT NULL,
  stp_mode        TEXT,
  maker_fee_rate  BIGINT NOT NULL DEFAULT 0,
  taker_fee_rate  BIGINT NOT NULL DEFAULT 0,
  fee_currency    TEXT,
  fee_model       TEXT NOT NULL DEFAULT 'flat',
  fee_tiers       JSONB,
  cb_window_secs  INT,
  cb_max_move_pct BIGINT,
  cb_cooldown_secs INT,
  state           TEXT NOT NULL DEFAULT 'open',
  created_by      TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
