// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: proto/engine/engine.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateMarketRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MarketId         string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Auction          bool                   `protobuf:"varint,2,opt,name=auction,proto3" json:"auction,omitempty"`                                             // run an opening call-auction before continuous trading
	AuctionPreopenMs int64                  `protobuf:"varint,3,opt,name=auction_preopen_ms,json=auctionPreopenMs,proto3" json:"auction_preopen_ms,omitempty"` // pre-open accumulation window before the auction clears
	ReferencePrice   string                 `protobuf:"bytes,4,opt,name=reference_price,json=referencePrice,proto3" json:"reference_price,omitempty"`          // auction clearing-price tiebreaker (decimal string)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateMarketRequest) Reset() {
	*x = CreateMarketRequest{}
	mi := &file_proto_engine_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMarketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMarketRequest) ProtoMessage() {}

func (x *CreateMarketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMarketRequest.ProtoReflect.Descriptor instead.
func (*CreateMarketRequest) Descriptor() ([]byte, []int) {
	return file_proto_engine_engine_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMarketRequest) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *CreateMarketRequest) GetAuction() bool {
	if x != nil {
		return x.Auction
	}
	return false
}

func (x *CreateMarketRequest) GetAuctionPreopenMs() int64 {
	if x != nil {
		return x.AuctionPreopenMs
	}
	return 0
}

func (x *CreateMarketRequest) GetReferencePrice() string {
	if x != nil {
		return x.ReferencePrice
	}
	return ""
}

type CreateMarketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Created       bool                   `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"` // the market's engine state after creation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMarketResponse) Reset() {
	*x = CreateMarketResponse{}
	mi := &file_proto_engine_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMarketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMarketResponse) ProtoMessage() {}

func (x *CreateMarketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMarketResponse.ProtoReflect.Descriptor instead.
func (*CreateMarketResponse) Descriptor() ([]byte, []int) {
	return file_proto_engine_engine_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMarketResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

func (x *CreateMarketResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type PlaceOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Side          string                 `protobuf:"bytes,4,opt,name=side,proto3" json:"side,omitempty"`
	OrderType     string                 `protobuf:"bytes,5,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	Price         string                 `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	StopPrice     string                 `protobuf:"bytes,7,opt,name=stop_price,json=stopPrice,proto3" json:"stop_price,omitempty"`
	Qty           string                 `protobuf:"bytes,8,opt,name=qty,proto3" json:"qty,omitempty"`
	DisplayQty    string                 `protobuf:"bytes,9,opt,name=display_qty,json=displayQty,proto3" json:"display_qty,omitempty"`
	Tif           string                 `protobuf:"bytes,10,opt,name=tif,proto3" json:"tif,omitempty"`
	ExpireAt      int64                  `protobuf:"varint,11,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	Flags         []string               `protobuf:"bytes,12,rep,name=flags,proto3" json:"flags,omitempty"`
	StpMode       string                 `protobuf:"bytes,13,opt,name=stp_mode,json=stpMode,proto3" json:"stp_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderRequest) Reset() {
	*x = PlaceOrderRequest{}
	mi := &file_proto_engine_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderRequest) ProtoMessage() {}

func (x *PlaceOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderRequest.ProtoReflect.Descriptor instead.
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_engine_engine_proto_rawDescGZIP(), []int{2}
}

func (x *PlaceOrderRequest) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *PlaceOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PlaceOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlaceOrderRequest) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *PlaceOrderRequest) GetOrderType() string {
	if x != nil {
		return x.OrderType
	}
	return ""
}

func (x *PlaceOrderRequest) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *PlaceOrderRequest) GetStopPrice() string {
	if x != nil {
		return x.StopPrice
	}
	return ""
}

func (x *PlaceOrderRequest) GetQty() string {
	if x != nil {
		return x.Qty
	}
	return ""
}

func (x *PlaceOrderRequest) GetDisplayQty() string {
	if x != nil {
		return x.DisplayQty
	}
	return ""
}

func (x *PlaceOrderRequest) GetTif() string {
	if x != nil {
		return x.Tif
	}
	return ""
}

func (x *PlaceOrderRequest) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

func (x *PlaceOrderRequest) GetFlags() []string {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *PlaceOrderRequest) GetStpMode() string {
	if x != nil {
		return x.StpMode
	}
	return ""
}

type PlaceOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	SeqNum        uint64                 `protobuf:"varint,2,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderResponse) Reset() {
	*x = PlaceOrderResponse{}
	mi := &file_proto_engine_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderResponse) ProtoMessage() {}

func (x *PlaceOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderResponse.ProtoReflect.Descriptor instead.
func (*PlaceOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_engine_engine_proto_rawDescGZIP(), []int{3}
}

func (x *PlaceOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PlaceOrderResponse) GetSeqNum() uint64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *PlaceOrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PlaceOrderResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_proto_engine_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_engine_engine_proto_rawDescGZIP(), []int{4}
}

func (x *CancelOrderRequest) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *CancelOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CancelOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_proto_engine_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_engine_engine_proto_rawDescGZIP(), []int{5}
}

func (x *CancelOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CancelOrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CancelOrderResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetDepthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Levels        int32                  `protobuf:"varint,2,opt,name=levels,proto3" json:"levels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepthRequest) Reset() {
	*x = GetDepthRequest{}
	mi := &file_proto_engine_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepthRequest) ProtoMessage() {}

func (x *GetDepthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepthRequest.ProtoReflect.Descriptor instead.
func (*GetDepthRequest) Descriptor() ([]byte, []int) {
	return file_proto_engine_engine_proto_rawDescGZIP(), []int{6}
}

func (x *GetDepthRequest) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *GetDepthRequest) GetLevels() int32 {
	if x != nil {
		return x.Levels
	}
	return 0
}

type GetDepthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bids          []*DepthLevel          `protobuf:"bytes,1,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks          []*DepthLevel          `protobuf:"bytes,2,rep,name=asks,proto3" json:"asks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepthResponse) Reset() {
	*x = GetDepthResponse{}
	mi := &file_proto_engine_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepthResponse) ProtoMessage() {}

func (x *GetDepthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepthResponse.ProtoReflect.Descriptor instead.
func (*GetDepthResponse) Descriptor() ([]byte, []int) {
	return file_proto_engine_engine_proto_rawDescGZIP(), []int{7}
}

func (x *GetDepthResponse) GetBids() []*DepthLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *GetDepthResponse) GetAsks() []*DepthLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

type DepthLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         string                 `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	TotalQty      string                 `protobuf:"bytes,2,opt,name=total_qty,json=totalQty,proto3" json:"total_qty,omitempty"`
	DisplayQty    string                 `protobuf:"bytes,3,opt,name=display_qty,json=displayQty,proto3" json:"display_qty,omitempty"`
	OrderCount    int32                  `protobuf:"varint,4,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepthLevel) Reset() {
	*x = DepthLevel{}
	mi := &file_proto_engine_engine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepthLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepthLevel) ProtoMessage() {}

func (x *DepthLevel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_engine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepthLevel.ProtoReflect.Descriptor instead.
func (*DepthLevel) Descriptor() ([]byte, []int) {
	return file_proto_engine_engine_proto_rawDescGZIP(), []int{8}
}

func (x *DepthLevel) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *DepthLevel) GetTotalQty() string {
	if x != nil {
		return x.TotalQty
	}
	return ""
}

func (x *DepthLevel) GetDisplayQty() string {
	if x != nil {
		return x.DisplayQty
	}
	return ""
}

func (x *DepthLevel) GetOrderCount() int32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

type GetBBORequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBBORequest) Reset() {
	*x = GetBBORequest{}
	mi := &file_proto_engine_engine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBBORequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBBORequest) ProtoMessage() {}

func (x *GetBBORequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_engine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBBORequest.ProtoReflect.Descriptor instead.
func (*GetBBORequest) Descriptor() ([]byte, []int) {
	return file_proto_engine_engine_proto_rawDescGZIP(), []int{9}
}

func (x *GetBBORequest) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

type GetBBOResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bid           string                 `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`
	Ask           string                 `protobuf:"bytes,2,opt,name=ask,proto3" json:"ask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBBOResponse) Reset() {
	*x = GetBBOResponse{}
	mi := &file_proto_engine_engine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBBOResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBBOResponse) ProtoMessage() {}

func (x *GetBBOResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_engine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBBOResponse.ProtoReflect.Descriptor instead.
func (*GetBBOResponse) Descriptor() ([]byte, []int) {
	return file_proto_engine_engine_proto_rawDescGZIP(), []int{10}
}

func (x *GetBBOResponse) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *GetBBOResponse) GetAsk() string {
	if x != nil {
		return x.Ask
	}
	return ""
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_proto_engine_engine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_engine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_engine_engine_proto_rawDescGZIP(), []int{11}
}

func (x *GetStatsRequest) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

type GetStatsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MarketId          string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	State             string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	OrderSeq          uint64                 `protobuf:"varint,3,opt,name=order_seq,json=orderSeq,proto3" json:"order_seq,omitempty"`
	EventSeq          uint64                 `protobuf:"varint,4,opt,name=event_seq,json=eventSeq,proto3" json:"event_seq,omitempty"`
	OpenOrders        int32                  `protobuf:"varint,5,opt,name=open_orders,json=openOrders,proto3" json:"open_orders,omitempty"`
	StopOrders        int32                  `protobuf:"varint,6,opt,name=stop_orders,json=stopOrders,proto3" json:"stop_orders,omitempty"`
	BidLevels         int32                  `protobuf:"varint,7,opt,name=bid_levels,json=bidLevels,proto3" json:"bid_levels,omitempty"`
	AskLevels         int32                  `protobuf:"varint,8,opt,name=ask_levels,json=askLevels,proto3" json:"ask_levels,omitempty"`
	NodePoolUsed      int32                  `protobuf:"varint,9,opt,name=node_pool_used,json=nodePoolUsed,proto3" json:"node_pool_used,omitempty"`
	NodePoolCapacity  int32                  `protobuf:"varint,10,opt,name=node_pool_capacity,json=nodePoolCapacity,proto3" json:"node_pool_capacity,omitempty"`
	LevelPoolUsed     int32                  `protobuf:"varint,11,opt,name=level_pool_used,json=levelPoolUsed,proto3" json:"level_pool_used,omitempty"`
	LevelPoolCapacity int32                  `protobuf:"varint,12,opt,name=level_pool_capacity,json=levelPoolCapacity,proto3" json:"level_pool_capacity,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_proto_engine_engine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_engine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_engine_engine_proto_rawDescGZIP(), []int{12}
}

func (x *GetStatsResponse) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *GetStatsResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GetStatsResponse) GetOrderSeq() uint64 {
	if x != nil {
		return x.OrderSeq
	}
	return 0
}

func (x *GetStatsResponse) GetEventSeq() uint64 {
	if x != nil {
		return x.EventSeq
	}
	return 0
}

func (x *GetStatsResponse) GetOpenOrders() int32 {
	if x != nil {
		return x.OpenOrders
	}
	return 0
}

func (x *GetStatsResponse) GetStopOrders() int32 {
	if x != nil {
		return x.StopOrders
	}
	return 0
}

func (x *GetStatsResponse) GetBidLevels() int32 {
	if x != nil {
		return x.BidLevels
	}
	return 0
}

func (x *GetStatsResponse) GetAskLevels() int32 {
	if x != nil {
		return x.AskLevels
	}
	return 0
}

func (x *GetStatsResponse) GetNodePoolUsed() int32 {
	if x != nil {
		return x.NodePoolUsed
	}
	return 0
}

func (x *GetStatsResponse) GetNodePoolCapacity() int32 {
	if x != nil {
		return x.NodePoolCapacity
	}
	return 0
}

func (x *GetStatsResponse) GetLevelPoolUsed() int32 {
	if x != nil {
		return x.LevelPoolUsed
	}
	return 0
}

func (x *GetStatsResponse) GetLevelPoolCapacity() int32 {
	if x != nil {
		return x.LevelPoolCapacity
	}
	return 0
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_proto_engine_engine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_engine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_engine_engine_proto_rawDescGZIP(), []int{13}
}

func (x *StreamEventsRequest) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

type EngineEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	SeqNum        uint64                 `protobuf:"varint,3,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EngineEvent) Reset() {
	*x = EngineEvent{}
	mi := &file_proto_engine_engine_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngineEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineEvent) ProtoMessage() {}

func (x *EngineEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_engine_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineEvent.ProtoReflect.Descriptor instead.
func (*EngineEvent) Descriptor() ([]byte, []int) {
	return file_proto_engine_engine_proto_rawDescGZIP(), []int{14}
}

func (x *EngineEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EngineEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EngineEvent) GetSeqNum() uint64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

var File_proto_engine_engine_proto protoreflect.FileDescriptor

const file_proto_engine_engine_proto_rawDesc = "" +
	"\n" +
	"\x19proto/engine/engine.proto\x12\tengine.v1\"\xa3\x01\n" +
	"\x13CreateMarketRequest\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x18\n" +
	"\aauction\x18\x02 \x01(\bR\aauction\x12,\n" +
	"\x12auction_preopen_ms\x18\x03 \x01(\x03R\x10auctionPreopenMs\x12'\n" +
	"\x0freference_price\x18\x04 \x01(\tR\x0ereferencePrice\"F\n" +
	"\x14CreateMarketResponse\x12\x18\n" +
	"\acreated\x18\x01 \x01(\bR\acreated\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"\xdf\x02\n" +
	"\x11PlaceOrderRequest\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x12\n" +
	"\x04side\x18\x04 \x01(\tR\x04side\x12\x1d\n" +
	"\n" +
	"order_type\x18\x05 \x01(\tR\torderType\x12\x14\n" +
	"\x05price\x18\x06 \x01(\tR\x05price\x12\x1d\n" +
	"\n" +
	"stop_price\x18\a \x01(\tR\tstopPrice\x12\x10\n" +
	"\x03qty\x18\b \x01(\tR\x03qty\x12\x1f\n" +
	"\vdisplay_qty\x18\t \x01(\tR\n" +
	"displayQty\x12\x10\n" +
	"\x03tif\x18\n" +
	" \x01(\tR\x03tif\x12\x1b\n" +
	"\texpire_at\x18\v \x01(\x03R\bexpireAt\x12\x14\n" +
	"\x05flags\x18\f \x03(\tR\x05flags\x12\x19\n" +
	"\bstp_mode\x18\r \x01(\tR\astpMode\"x\n" +
	"\x12PlaceOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\aseq_num\x18\x02 \x01(\x04R\x06seqNum\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"e\n" +
	"\x12CancelOrderRequest\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"`\n" +
	"\x13CancelOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"F\n" +
	"\x0fGetDepthRequest\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x16\n" +
	"\x06levels\x18\x02 \x01(\x05R\x06levels\"h\n" +
	"\x10GetDepthResponse\x12)\n" +
	"\x04bids\x18\x01 \x03(\v2\x15.engine.v1.DepthLevelR\x04bids\x12)\n" +
	"\x04asks\x18\x02 \x03(\v2\x15.engine.v1.DepthLevelR\x04asks\"\x81\x01\n" +
	"\n" +
	"DepthLevel\x12\x14\n" +
	"\x05price\x18\x01 \x01(\tR\x05price\x12\x1b\n" +
	"\ttotal_qty\x18\x02 \x01(\tR\btotalQty\x12\x1f\n" +
	"\vdisplay_qty\x18\x03 \x01(\tR\n" +
	"displayQty\x12\x1f\n" +
	"\vorder_count\x18\x04 \x01(\x05R\n" +
	"orderCount\",\n" +
	"\rGetBBORequest\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\"4\n" +
	"\x0eGetBBOResponse\x12\x10\n" +
	"\x03bid\x18\x01 \x01(\tR\x03bid\x12\x10\n" +
	"\x03ask\x18\x02 \x01(\tR\x03ask\".\n" +
	"\x0fGetStatsRequest\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\"\xab\x03\n" +
	"\x10GetStatsResponse\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1b\n" +
	"\torder_seq\x18\x03 \x01(\x04R\borderSeq\x12\x1b\n" +
	"\tevent_seq\x18\x04 \x01(\x04R\beventSeq\x12\x1f\n" +
	"\vopen_orders\x18\x05 \x01(\x05R\n" +
	"openOrders\x12\x1f\n" +
	"\vstop_orders\x18\x06 \x01(\x05R\n" +
	"stopOrders\x12\x1d\n" +
	"\n" +
	"bid_levels\x18\a \x01(\x05R\tbidLevels\x12\x1d\n" +
	"\n" +
	"ask_levels\x18\b \x01(\x05R\taskLevels\x12$\n" +
	"\x0enode_pool_used\x18\t \x01(\x05R\fnodePoolUsed\x12,\n" +
	"\x12node_pool_capacity\x18\n" +
	" \x01(\x05R\x10nodePoolCapacity\x12&\n" +
	"\x0flevel_pool_used\x18\v \x01(\x05R\rlevelPoolUsed\x12.\n" +
	"\x13level_pool_capacity\x18\f \x01(\x05R\x11levelPoolCapacity\"2\n" +
	"\x13StreamEventsRequest\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\"_\n" +
	"\vEngineEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x17\n" +
	"\aseq_num\x18\x03 \x01(\x04R\x06seqNum2\x8c\x04\n" +
	"\rEngineService\x12I\n" +
	"\n" +
	"PlaceOrder\x12\x1c.engine.v1.PlaceOrderRequest\x1a\x1d.engine.v1.PlaceOrderResponse\x12L\n" +
	"\vCancelOrder\x12\x1d.engine.v1.CancelOrderRequest\x1a\x1e.engine.v1.CancelOrderResponse\x12C\n" +
	"\bGetDepth\x12\x1a.engine.v1.GetDepthRequest\x1a\x1b.engine.v1.GetDepthResponse\x12=\n" +
	"\x06GetBBO\x12\x18.engine.v1.GetBBORequest\x1a\x19.engine.v1.GetBBOResponse\x12C\n" +
	"\bGetStats\x12\x1a.engine.v1.GetStatsRequest\x1a\x1b.engine.v1.GetStatsResponse\x12H\n" +
	"\fStreamEvents\x12\x1e.engine.v1.StreamEventsRequest\x1a\x16.engine.v1.EngineEvent0\x01\x12O\n" +
	"\fCreateMarket\x12\x1e.engine.v1.CreateMarketRequest\x1a\x1f.engine.v1.CreateMarketResponseB6Z4github.com/thorlaidanegg/clob-server/proto/engine/v1b\x06proto3"

var (
	file_proto_engine_engine_proto_rawDescOnce sync.Once
	file_proto_engine_engine_proto_rawDescData []byte
)

func file_proto_engine_engine_proto_rawDescGZIP() []byte {
	file_proto_engine_engine_proto_rawDescOnce.Do(func() {
		file_proto_engine_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_engine_engine_proto_rawDesc), len(file_proto_engine_engine_proto_rawDesc)))
	})
	return file_proto_engine_engine_proto_rawDescData
}

var file_proto_engine_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_engine_engine_proto_goTypes = []any{
	(*CreateMarketRequest)(nil),  // 0: engine.v1.CreateMarketRequest
	(*CreateMarketResponse)(nil), // 1: engine.v1.CreateMarketResponse
	(*PlaceOrderRequest)(nil),    // 2: engine.v1.PlaceOrderRequest
	(*PlaceOrderResponse)(nil),   // 3: engine.v1.PlaceOrderResponse
	(*CancelOrderRequest)(nil),   // 4: engine.v1.CancelOrderRequest
	(*CancelOrderResponse)(nil),  // 5: engine.v1.CancelOrderResponse
	(*GetDepthRequest)(nil),      // 6: engine.v1.GetDepthRequest
	(*GetDepthResponse)(nil),     // 7: engine.v1.GetDepthResponse
	(*DepthLevel)(nil),           // 8: engine.v1.DepthLevel
	(*GetBBORequest)(nil),        // 9: engine.v1.GetBBORequest
	(*GetBBOResponse)(nil),       // 10: engine.v1.GetBBOResponse
	(*GetStatsRequest)(nil),      // 11: engine.v1.GetStatsRequest
	(*GetStatsResponse)(nil),     // 12: engine.v1.GetStatsResponse
	(*StreamEventsRequest)(nil),  // 13: engine.v1.StreamEventsRequest
	(*EngineEvent)(nil),          // 14: engine.v1.EngineEvent
}
var file_proto_engine_engine_proto_depIdxs = []int32{
	8,  // 0: engine.v1.GetDepthResponse.bids:type_name -> engine.v1.DepthLevel
	8,  // 1: engine.v1.GetDepthResponse.asks:type_name -> engine.v1.DepthLevel
	2,  // 2: engine.v1.EngineService.PlaceOrder:input_type -> engine.v1.PlaceOrderRequest
	4,  // 3: engine.v1.EngineService.CancelOrder:input_type -> engine.v1.CancelOrderRequest
	6,  // 4: engine.v1.EngineService.GetDepth:input_type -> engine.v1.GetDepthRequest
	9,  // 5: engine.v1.EngineService.GetBBO:input_type -> engine.v1.GetBBORequest
	11, // 6: engine.v1.EngineService.GetStats:input_type -> engine.v1.GetStatsRequest
	13, // 7: engine.v1.EngineService.StreamEvents:input_type -> engine.v1.StreamEventsRequest
	0,  // 8: engine.v1.EngineService.CreateMarket:input_type -> engine.v1.CreateMarketRequest
	3,  // 9: engine.v1.EngineService.PlaceOrder:output_type -> engine.v1.PlaceOrderResponse
	5,  // 10: engine.v1.EngineService.CancelOrder:output_type -> engine.v1.CancelOrderResponse
	7,  // 11: engine.v1.EngineService.GetDepth:output_type -> engine.v1.GetDepthResponse
	10, // 12: engine.v1.EngineService.GetBBO:output_type -> engine.v1.GetBBOResponse
	12, // 13: engine.v1.EngineService.GetStats:output_type -> engine.v1.GetStatsResponse
	14, // 14: engine.v1.EngineService.StreamEvents:output_type -> engine.v1.EngineEvent
	1,  // 15: engine.v1.EngineService.CreateMarket:output_type -> engine.v1.CreateMarketResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_engine_engine_proto_init() }
func file_proto_engine_engine_proto_init() {
	if File_proto_engine_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_engine_engine_proto_rawDesc), len(file_proto_engine_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_engine_engine_proto_goTypes,
		DependencyIndexes: file_proto_engine_engine_proto_depIdxs,
		MessageInfos:      file_proto_engine_engine_proto_msgTypes,
	}.Build()
	File_proto_engine_engine_proto = out.File
	file_proto_engine_engine_proto_goTypes = nil
	file_proto_engine_engine_proto_depIdxs = nil
}
